export const SERVER_ERROR = "SERVER_ERROR"
export const ADD_DEFAULT_CALENDAR = "ADD_DEFAULT_CALENDAR"
export const UPDATE_CALENDAR_FIELDS = "UPDATE_CALENDAR_FIELDS"
export const DELETE_CALENDAR_ITEM = "DELETE_CALENDAR_ITEM"