// Calendar
export const SERVER_ERROR = "SERVER_ERROR"
export const ADD_DEFAULT_CALENDAR = "ADD_DEFAULT_CALENDAR"
export const UPDATE_CALENDAR_FIELDS = "UPDATE_CALENDAR_FIELDS"
export const DELETE_CALENDAR_ITEM = "DELETE_CALENDAR_ITEM"
export const ADD_CALENDAR_ITEM = "ADD_CALENDAR_ITEM"

// User
export const ADD_DEFAULT_USER = "ADD_DEFAULT_USER"

//Quiz
export const QUIZ_RESULTS = "QUIZ_RESULTS"
export const ADD_QUIZZ_ITEM = "ADD_QUIZZ_ITEM"
